### ISSUE TITLE
Synchronize with Lancer Clocks

### ISSUE THREAD

**Issue by danielmacapa** [unsoluble/smalltime#119]
Hello. Your work is already formidable and it helps us a lot in our games, increasing the fun of the group. Thank you! However, there's nothing it can't improve on, and it would be beautiful, wonderful, wonderful if Small Time would talk with Lancer Clocks to advance the time as the Lancer Clocks clock advance. He is great for managing quartes of day in the system Forbidden Lands.

**Comment by unsoluble** [comment]
Thanks, glad you're enjoying the module!

Can you elaborate on how exactly the Lancer Clocks module interacts with game time? I can't tell what it's supposed to be doing from just reading the project page.

**Comment by Argonius-Angelus** [comment]
Hey, dev for Lancer Clocks here (this was recently linked to me in my Discord DMs). In essence, Lancer Clocks is designed to be a method of tracking resources, progress, or just the passage of time (said timescale is arbitrary). If you've played Blades in the Dark (what the original Clocks module was designed for) or Lancer (what my fork was styled after), you'd get a decent idea of what the clocks can be used to track.

Personally, I feel like, while it would be pretty cool to progress the time of day by progressing the clock (filling in segments), it'd definitely be better to do as a macro rather than integrate functionality inside this module.

**Comment by unsoluble** [comment]
Cool, thanks for the explanation. All it would take for your segment-filling to change the time of day would be to use the core API's `game.time.advance()` — SmallTime (and other time/date modules) runs off this core clock.
