### ISSUE TITLE
Relative position of the SmallTime window

### ISSUE THREAD

**Issue by Juanfrank** [unsoluble/smalltime#45]
Hello.-

There's this weird behavior where the relative position of the smalltime position changes when your browser's size is changed (ex. by using F11). 

This proves to be kind of annoying since my SmallTime window is placed on the bottom of the screen, and switching to fullscreen mode in my browser shifts the Smalltime's window location relative to the bottom, leaving a huge gap in between.

Is it possible to change the Smalltime window's relative position so that it behaves like the Hotbar (where it retains the relative position to the bottom) or Monk's TokenBar (I don't like to compare, but I see no other way to state what's the intended position behaviour I'm looking for)

Thanks!!

**Comment by unsoluble** [comment]
Yeah this one's been on my to-investigate list since the beginning. It's not straightforward to solve, because the user's intent is not clear with respect to the desired position -- I have no way of knowing whether it's _intended_ to be relative to the top or the bottom of the viewport. (This is why I implemented the pinning zone above the Players list, so you can have at least one dedicated space that does stick to the bottom.)

**Comment by Juanfrank** [comment]
I see where you're getting at. I'm comfortable with whatever -if any- solution you come up with!

Thanks for the early response!

**Comment by unsoluble** [comment]
Have revisited this a few times now, and it's just going to be too much effort for very little gain. Going to `wontfix` this one for now.
