### ISSUE TITLE
Feature request: Add ability to display temperature and weather

### ISSUE THREAD

**Issue by jstebenne** [unsoluble/smalltime#64]
I would like to be able to push weather and temperature information from inside Calendar/Weather, along with the tools to do more.

Here are some of the features I have in mind that this would allow me to build:

- Option to push weather info the Small Time (otherwise it might only be shown in the chat)
- Display approximate temperature to players (could be descriptions like "cold", "warm", "very hot")
  - If I get to a point I want to push this further, I might make it customizable for each character (if they are used to cold or the race comes from a hot place)
- Open a window when clicking on the temperature to display forecast (for GM and characters with special abilities)

C/W will still have the ability to output weather changes to chat, but displaying it with the current time of day would probably be nice.

**Comment by unsoluble** [comment]
Hmmmmmmmm.

My gut reaction to this is a pretty hard Nope, seems like feature creep a little too far for SmallTime's scope. I _really_ don't want to add anything else to the visible UI, and all my click surfaces are already loaded up. If I can think of some clever way of displaying this info without gumming up the works, it might be possible in theory, but this is probably better served by C/W's UI, since that'll be needed for the config anyway.

**Comment by apoapostolov** [comment]
@unsoluble Click on time to open date... click on date to rotate date and weather... provide hooks for ANOTHER module to provide weather information. This is amazing needed functionality but a rabbit hole of development of proper weather simulation with real world or fantasy parametrization. Whoever does it would benefit from importing the data to SmallTime to offload need to make widget UI UX.

**Comment by unsoluble** [comment]
> Click on time to open date... click on the date to rotate date and weather... 

Hah! I literally had a dream this morning about implementing it this way (I have far too many UI dreams). Get out of my head :)

**Comment by apoapostolov** [comment]
If you want even more UI bliss, when you rotate time to weather, the weather mod can even provide a wide image of the weather that fades through in place of the day cycle strip and then fades back to the day cycle strip when you return from weather to date.

**Comment by unsoluble** [comment]
Yeah if I'm going to do anything in this area it'd just be reading in a weather state from elsewhere and displaying it. But yep, certainly some possibilities there.

To tamper expectations, I probably won't start investigating this until Calendar/Weather has made its full metamorphosis into just Weather (or whatever it ends up being called).

**Comment by GenX187** [comment]
I have looked at the module (Weather Control) for V9. But for me personally, it goes in a different direction. I would like to actually set the weather and temperature as GM and then display this to the players.  It would be great if you could integrate this somehow, because currently I see no module what this small but for a trip important information provides to the players.

**Comment by unsoluble** [comment]
Thanks for your thoughts on this, but I can assure you I won't be adding any weather-manipulating UI to SmallTime. Very not within the module's scope.

**Comment by unsoluble** [comment]
SmallWeather module provides this now.
