### ISSUE TITLE
Feature request: agree with Simple Calendar on which tool bar "time" goes

### ISSUE THREAD

**Issue by scooper4711** [unsoluble/smalltime#77]
Simple Calendar places itself under Token Controls.
Smalltime places itself under Journal Notes.

Arguments could be made for either or neither of those options. One might even argue that the concept of "time" is a "measurement" and belongs under that tool set.

Regardless of where you two place yourself, I'd love it if you were both under the *same* tool set. :D

**Comment by scooper4711** [comment]
Link to https://github.com/vigoren/foundryvtt-simple-calendar/issues/193

**Comment by unsoluble** [comment]
SmallTime is under `Journal Notes` because it doesn't have anything to do with tokens or measured templates, and the `Lighting Controls` layer isn't available to non-GMs. If I had to guess, SC probably goes with `Token Controls` because it's the default and most commonly used, so is more accessible. SmallTime's toggle doesn't need anything like that kind of visibility, though.

So, short answer is: I'm not moving. :)
