### ISSUE TITLE
Add control / diffrent versions over color pallete

### ISSUE THREAD

**Issue by CCRPG** [unsoluble/smalltime#93]
Thanks for your work. Your module works great for my normal fantasy campaign. However, I'll be soon running gothic fantasy Curse of Strahd, and although this may sound incredibly petty it's too bright and happy. I would like to change the background "sky" to more gray mists overlook and make sun less bright if possible. Possibly make sky other colors for some otherworldy place. 

This is only a small enhancement, but I know it can be a pain to implement, so I fully understand if you don't find it useful enough to warrant work.   

Thanks

**Comment by Nmacpr** [comment]
@CCRPG I had the same idea too since I'm also running CoS. Just a quick fix with the help of unsolable above, but maybe this works for you too.

Used the hexcode #d3d3d3 in both sunrise end and sunset start (in the smalltime.css file in styles), and used this quick edited 'pale' sun from the files in this github. Will have to upload it here as a png, but it needs to be converted to a .webp to work and the previous sun replaced in images (just google a converter for that).

![Screenshot 2021-12-16 213622](https://user-images.githubusercontent.com/86777976/146452993-f9dd485b-cde8-4d05-8ab0-5f4baa67b172.jpg)
![sun](https://user-images.githubusercontent.com/86777976/146453083-c20317f7-4b0a-4cf8-b1cc-32d4d96dbd26.png)
